#!/usr/bin/env python3
"""Generate the tiny deterministic A9TAS1 archive embedded in the G10 APK."""

from __future__ import annotations

import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))

from a9tas_recording_v1 import encode_archive  # noqa: E402
from test_a9tas_recording_v1 import make_manifest, make_recording  # noqa: E402


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: make_g10_archive_selftest_v1.py OUTPUT")
    output = Path(sys.argv[1])
    recording = make_recording()
    blob = encode_archive(make_manifest(recording), recording)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".pending")
    temporary.write_bytes(blob)
    temporary.replace(output)
    print(f"G10_ARCHIVE_SELFTEST_GENERATED bytes={len(blob)} output={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
