#!/usr/bin/env python3
"""Offline equivalence checks for the on-device ARM64 profile resolver catalog."""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import resolve_a9_build_profile_v1 as resolver
import generate_g8_runtime_build_profile_v1 as compiler


def require(value: bool, message: str) -> None:
    if not value:
        raise AssertionError(message)


def main() -> int:
    argument_parser = argparse.ArgumentParser()
    argument_parser.add_argument(
        "--deep", action="store_true",
        help="regenerate the catalog and rescan the full reference ELF topology")
    args = argument_parser.parse_args()
    reference = ROOT / "build/profile-autogen-reference/lib/arm64-v8a/libAsphalt9.so"
    catalog = ROOT / "src/a9_arm64_profile_signature_catalog_v1.h"
    builtin = ROOT / "A9TasAndroid/app/src/main/assets/profiles/671522d4614abcce.a9profile.bin"
    require(reference.is_file(), "reference ELF is unavailable")
    if args.deep:
        with tempfile.TemporaryDirectory() as directory:
            generated = pathlib.Path(directory) / "catalog.h"
            subprocess.run([sys.executable, str(ROOT / "tools/generate_arm64_profile_catalog_v1.py"),
                            "--reference-elf", str(reference), "--output", str(generated)],
                           check=True, stdout=subprocess.DEVNULL)
            require(generated.read_bytes() == catalog.read_bytes(),
                    "checked-in ARM64 signature catalog drifted")

    accepted_source = ROOT / "build/generated-profiles/reference.a9profile.json"
    source = accepted_source.read_bytes()
    document = json.loads(source)
    blob = compiler.compile_profile(document, source)
    expected = builtin.read_bytes()
    require(len(blob) == len(expected) == 3104, "reference Profile size drift")
    require(blob[:288] == expected[:288] and blob[320:] == expected[320:],
            "resolver-generated runtime fields differ from the accepted reference Profile")

    # A semantic group supplies the coarse relocation delta.  Individual
    # functions may move locally when a channel build changes literal-pool or
    # cold-block layout, so selection must accept exactly one nearby match and
    # reject ambiguity.  This is deliberately bounded and is not a nearest-hit
    # heuristic.
    require(resolver.select_role_hit("synthetic", [0x2000], 0x1FD0) == 0x2000,
            "bounded local role drift was rejected")
    try:
        resolver.select_role_hit("synthetic", [0x1FE0, 0x2020], 0x2000)
    except ValueError:
        pass
    else:
        raise AssertionError("ambiguous local role drift was accepted")

    # When the locally captured Huawei ELF is available, prove that the
    # repaired resolver produces the exact accepted runtime ABI.  Only the
    # source-document SHA field may differ because paths and diagnostic hit
    # counts are provenance, not runtime addresses.
    huawei_result = ROOT / "evidence/unknown-profile/huawei-autogen-after.json"
    huawei_builtin = ROOT / "build/generated-profiles/439fd7f94ef570d9.a9profile.bin"
    huawei_runtime_equal = 0
    if huawei_result.is_file() and huawei_builtin.is_file():
        huawei_source = huawei_result.read_bytes()
        huawei_blob = compiler.compile_profile(json.loads(huawei_source), huawei_source)
        accepted_huawei = huawei_builtin.read_bytes()
        require(len(huawei_blob) == len(accepted_huawei) == 3104,
                "Huawei Profile size drift")
        require(huawei_blob[:288] == accepted_huawei[:288] and
                huawei_blob[320:] == accepted_huawei[320:],
                "autogenerated Huawei runtime fields differ from accepted Profile")
        huawei_runtime_equal = 1

    catalog_text = catalog.read_text(encoding="utf-8")
    for token in ("kCatalogSha", "kRoles =", "kVtables =", "practice_vptr0",
                  "practice_vptr588", "practice_vptr6c0", "practice_vptr718",
                  "practice_vptr748"):
        require(token in catalog_text, f"checked-in signature catalog missing: {token}")
    if args.deep:
        elf = resolver.Elf(reference)
        practice = [0x812FAD8, 0x812FCB8, 0x812FE30, 0x812FEC0, 0x812FF88]
        wanted: set[int] = set()
        slot_maps: dict[int, list[tuple[int, int]]] = {}
        for base in practice:
            slots = []
            for slot in range(0, resolver.VTABLE_SCAN_SIZE, 8):
                pointer = int.from_bytes(elf.bytes_at_rva(base + slot, 8), "little")
                if elf.executable_rva(pointer, resolver.SIGNATURE_SIZE):
                    slots.append((slot, pointer)); wanted.add(pointer)
            slot_maps[base] = slots
        occurrences = elf.pointer_occurrence_index(wanted)
        import collections
        for base, slots in slot_maps.items():
            votes: collections.Counter[int] = collections.Counter()
            for slot, pointer in slots:
                for location in occurrences.get(pointer, []):
                    votes[location - slot] += 1
            require(votes and votes[base] == max(votes.values()) and
                    sum(score == max(votes.values()) for score in votes.values()) == 1,
                    f"practice vtable 0x{base:x} is not structurally unique")
    source_text = (ROOT / "src/android_arm64_profile_autogen_v1.cpp").read_text()
    for token in ("ResolveRoles", "ResolveVtables", "ResolveRelationships",
                  "RoleSignatureMatches", "SelectRoleHit", "kMaxRoleLocalDrift",
                  "complete_practice_vote", "practice vtable relative layout changed",
                  "kLifecycleVtableCount", "profile_abi::Valid", "passed=1"):
        require(token in source_text, f"native resolver contract missing: {token}")
    print("ARM64_PROFILE_AUTOGEN_SELFTEST passed=1 "
          f"deep={int(args.deep)} catalog_contract=1 reference_runtime_equal=1 "
          f"huawei_runtime_equal={huawei_runtime_equal} local_drift_fail_closed=1 "
          "practice_vtables=5 channel_literals=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
